// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMGD.Models;

public partial class article
{
    [Key]
    [StringLength(8)]
    public string article_number { get; set; }

    [Required]
    [StringLength(100)]
    public string title { get; set; }

    [Required]
    public string article_content { get; set; }

    [Required]
    [StringLength(50)]
    public string email { get; set; }

    [Required]
    [StringLength(20)]
    public string username { get; set; }
}