// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMGD.Models;

public partial class likely
{
    [Key]
    [StringLength(8)]
    public string article_number { get; set; }

    [Required]
    [Column("likely")]
    [StringLength(8)]
    public string likely1 { get; set; }
}