// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MMGD.Models;

public partial class userData
{
    [Key]
    [StringLength(50)]
    public string email { get; set; }

    [Required]
    [StringLength(20)]
    public string username { get; set; }

    [Required]
    [StringLength(20)]
    public string pwd { get; set; }
}